Fix some pipelines, rm credentials as variables in packer templates since, they will be passed in the GH actions

diff --git a/.github/workflows/build-digital-ocean.yml b/.github/workflows/build-digital-ocean.yml
--- a/.github/workflows/build-digital-ocean.yml
+++ b/.github/workflows/build-digital-ocean.yml
@@ -35,11 +35,6 @@ jobs:
         with:
           version: ${{ env.PACKER_VERSION }}
 
-      - name: Configure Digital Ocean Credentials
-        uses: digitalocean/action-doctl@v2
-        with:
-          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
-
       - name: Build Image
         working-directory: ./digital-ocean/templates
         run: |
@@ -53,6 +48,14 @@ jobs:
           log_warning() { printf "${ORANGE}[WARNING] %s${RESET}\n" "$1"; }
           log_error() { printf "${RED}[ERROR] %s${RESET}\n" "$1"; }
           log_info() { printf "[INFO] %s\n" "$1"; }
+
+          # Configure Digital Ocean credentials
+          log_info "Configuring Digital Ocean credentials..."
+          export DIGITALOCEAN_ACCESS_TOKEN="${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" || {
+            log_error "Failed to configure Digital Ocean credentials!"
+            exit 1
+          }
+          log_success "Digital Ocean credentials configured successfully."
 
           # Run Packer
           log_info "Initializing Packer build..."
